# Generated by Django 5.0.1 on 2024-01-31 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_usertasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userTasks',
        ),
    ]
