# Generated by Django 5.0.1 on 2024-01-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_rename_tarefa_usuario_tarefausuario_tarefa_trefa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tarefaUsuario',
        ),
    ]
